echo "Hello Young Minds Team"
echo "Currently we are learning Git Hub"
echo "This is our github script"
echo "Welcome to the Young Minds"
echo "Hello team, we are learning branching"
echo "Good Morning"
echo "I am devOps Engineer"