echo "Hello Young Minds Team"
echo "Currently we are learning Git Hub"
echo "This is our github script"
echo "Welcome to the Young Minds"
echo "Hello team, we are learning branching"
echo "Today we are learning Git commands"
echo "We are creating a new branch"
echo "We are also learning how to resolve merge conflicts"
echo "Hello team, we are learning git rebase"
echo "Today we are learning Git rebase command in practical way"

